-- 10. & 11.

CREATE TABLE cusca (
    id_cusca NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacitate NUMBER(4,2) NOT NULL CHECK (capacitate > 1),
    locatie VARCHAR2(10) DEFAULT 'interior' CHECK (locatie IN ('interior', 'exterior')) 
);

CREATE TABLE angajat (
    id_angajat NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(50) NOT NULL,
    prenume VARCHAR2(50) NOT NULL,
    telefon VARCHAR2(15) NOT NULL UNIQUE,
    email VARCHAR2(255) NOT NULL UNIQUE,
    data_angajare DATE DEFAULT SYSDATE
);

CREATE TABLE veterinar (
    id_angajat NUMBER PRIMARY KEY,
    specializare VARCHAR2(100) DEFAULT 'generalist',
    FOREIGN KEY (id_angajat) REFERENCES angajat(id_angajat)
);

CREATE TABLE receptioner (
    id_angajat NUMBER PRIMARY KEY,
    tura_preferata VARCHAR2(50),
    FOREIGN KEY (id_angajat) REFERENCES angajat(id_angajat)
);

CREATE TABLE voluntar (
    id_angajat NUMBER PRIMARY KEY,
    ocupatie VARCHAR2(50),
    FOREIGN KEY (id_angajat) REFERENCES angajat(id_angajat)
);

CREATE TABLE animal (
    id_animal NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cusca NUMBER,
    nume VARCHAR2(50),
    data_nastere DATE NOT NULL,
    specie VARCHAR2(50) NOT NULL,
    rasa VARCHAR2(50),
    in_tratament NUMBER(1) DEFAULT 0 CHECK (in_tratament IN (0, 1)),
    data_aducere DATE DEFAULT SYSDATE,
    FOREIGN KEY (id_cusca) REFERENCES cusca(id_cusca)
);

CREATE TABLE client (
    id_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(50) NOT NULL,
    prenume VARCHAR2(50) NOT NULL,
    telefon VARCHAR2(15) UNIQUE,
    email VARCHAR2(255) UNIQUE,
    CONSTRAINT ck_contact CHECK (telefon IS NOT NULL OR email IS NOT NULL)
);

CREATE TABLE vizita (
    id_vizita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client NUMBER NOT NULL,
    data_ORA TIMESTAMP DEFAULT SYSTIMESTAMP,
    detalii VARCHAR2(255),
    FOREIGN KEY (id_client) REFERENCES client(id_client)
);

CREATE TABLE vizita_animal (
    id_vizita NUMBER,
    id_animal NUMBER,
    PRIMARY KEY (id_vizita, id_animal),
    FOREIGN KEY (id_vizita) REFERENCES vizita(id_vizita),
    FOREIGN KEY (id_animal) REFERENCES animal(id_animal)
);

CREATE TABLE adoptie (
    id_adoptie NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_adoptator NUMBER NOT NULL,
    id_animal NUMBER NOT NULL,
    id_angajat NUMBER NOT NULL,
    data_adoptie DATE DEFAULT SYSDATE,
    FOREIGN KEY (id_adoptator) REFERENCES client(id_client),
    FOREIGN KEY (id_animal) REFERENCES animal(id_animal),
    FOREIGN KEY (id_angajat) REFERENCES angajat(id_angajat)
);

CREATE TABLE tranzactie (
    id_tranzactie NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_angajat NUMBER,
    suma NUMBER(10, 2) NOT NULL,
    data_ora TIMESTAMP DEFAULT SYSTIMESTAMP,
    detalii VARCHAR2(255),
    FOREIGN KEY (id_angajat) REFERENCES angajat(id_angajat),
    CONSTRAINT ck_angajat_tranzactie CHECK (id_angajat IS NOT NULL OR suma <= 500)
);

CREATE TABLE aprovizionare_hrana (
    id_aprovizionare NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tranzactie NUMBER,
    data_ora TIMESTAMP DEFAULT SYSTIMESTAMP,
    furnizor VARCHAR2(100),
    FOREIGN KEY (id_tranzactie) REFERENCES tranzactie(id_tranzactie)
);

CREATE TABLE hrana (
    id_hrana NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tip_hrana VARCHAR2(100) NOT NULL,
    firma VARCHAR2(100) NOT NULL,
    denumire VARCHAR2(100),
    detalii VARCHAR2(255) 
);

CREATE TABLE comanda_hrana (
    id_hrana NUMBER,
    id_aprovizionare NUMBER,
    cantitate NUMBER(10, 3) NOT NULL,
    um VARCHAR2(10) NOT NULL,
    FOREIGN KEY (id_hrana) REFERENCES hrana(id_hrana),
    FOREIGN KEY (id_aprovizionare) REFERENCES aprovizionare_hrana(id_aprovizionare)
);

CREATE TABLE donatie (
    id_donatie NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client NUMBER NOT NULL,
    id_tranzactie NUMBER,
    id_aprovizionare NUMBER,
    FOREIGN KEY (id_client) REFERENCES client(id_client),
    FOREIGN KEY (id_tranzactie) REFERENCES tranzactie(id_tranzactie),
    FOREIGN KEY (id_aprovizionare) REFERENCES aprovizionare_hrana(id_aprovizionare)
);

CREATE TABLE program_zi (
    data DATE PRIMARY KEY,
    tip_zi VARCHAR2(50) NOT NULL
);

CREATE TABLE tura (
    id_angajat NUMBER, 
    data_ora TIMESTAMP,
    durata NUMBER(4, 2) NOT NULL,
    PRIMARY KEY (id_angajat, data_ora),
    FOREIGN KEY (id_angajat) REFERENCES angajat(id_angajat)
);